### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by M0sterHxck** [Ignitetch/AdvPhishing#1]
some account not popup sms OTP

**Comment by Ignitetch** [comment]
Hi

Please Explain In Brief with Screenshots. I pretty sure   To resolve this
issue.

Thanks

**Comment by Ignitetch** [comment]
I Think it can help you

**Comment by Ignitetch** [comment]
When victim enter his credentials, you need to go to original website and use those credentials to send real OTP to victim. Once he enter that OTP such OTP will also be there with you and you will be allowed to login the account before him.

**Comment by M0sterHxck** [comment]
please telegram : @autopingtester

**Comment by M0sterHxck** [comment]
thank for your project but some acc not OTP

**Comment by Ignitetch** [comment]
Hi
I know what you mean but the main thing is how I check which person are
enabled two factor or not ?
So I will put them all of us .
