### ISSUE TITLE
Error while trying instagram

### ISSUE THREAD

**Issue by AnuranjKrishnan** [Ignitetch/AdvPhishing#10]
There is an error while trying instagram.
ngrok link also doesn't shows up.
./instagram.sh: line 90: jq: command not found
(23) Failed writing body 
./instagram.sh: line 91: jq: command not found
(23) Failed writing body.

**Comment by AnuranjKrishnan** [comment]
![500001700417_195666](https://user-images.githubusercontent.com/43990594/79843910-717e4100-83aa-11ea-84a8-637d60fb0999.jpg)

**Comment by Ignitetch** [comment]
Hi

It is must to run confit file.
Please checkout tutorial on my github page and if you facing again some
error give me SC Then I help.

Thanks

**Comment by AnuranjKrishnan** [comment]
I tried it again and I tried it in 2019 version and 2020 version still the same problem exist. I also didn't get what you said about confit file.

**Comment by AnuranjKrishnan** [comment]
I have seen many tutorial videos you've provided on the youtube still it doesn't work. Can you please elaborate the solution for the problem I've encountered.

**Comment by Ignitetch** [comment]
Hi

Please try new 2.0 version but must trash all old files

Thanks

**Comment by AnuranjKrishnan** [comment]
![IMG_20200422_140456](https://user-images.githubusercontent.com/43990594/79960191-a6ef6100-8474-11ea-8ea4-e6f3b455ca84.jpg)
This is the new issue

**Comment by AnuranjKrishnan** [comment]
I'm running a 32 bit version of kali 2020

**Comment by Ignitetch** [comment]
Hi

Can you give me team viewer session


Thanks

**Comment by AnuranjKrishnan** [comment]
Ok what should I do

**Comment by AnuranjKrishnan** [comment]
Your ID

**Comment by AnuranjKrishnan** [comment]
Tell me whenever you are online and I'll tell my id

**Comment by Ignitetch** [comment]
Hii

Chat me personal: 9891924936
