### ISSUE TITLE
OTP not generating

### ISSUE THREAD

**Issue by Expert-Hacker** [Ignitetch/AdvPhishing#11]
OTP was not generating here for all tools

**Comment by Ignitetch** [comment]
Hii

Alright ! When victim enter username and password you need to go orignal
webpage for send actual otp

Thanks

**Comment by KaravaliStudio** [comment]
Sir,
    For example, I selected whatsapp attack,then I sent the link to victim
phone ,the he will opens the link and enter phone number then I not getting
any OTP...even victim also no getting the link ... please look into it

**Comment by Ignitetch** [comment]
Hii

Yes ! I am saying same thing when victim enter whatsapp number you need to
enter those number on own WhatsApp then actual otp goes to victim so when
victim enter otp you need to enter otp then you will be loged in

Thanks

**Comment by KaravaliStudio** [comment]
Yes..I am getting your point..
But Whatsapp does not allow to access 2 account simultaneously..

**Comment by Ignitetch** [comment]
Hii

No you can be ! Whatsapp have inbuilt feature to add new number so once you
done it you will revive otp of new number.

Thanks

**Comment by KaravaliStudio** [comment]
Hi sir,
 Can you help me to fix this issue?

**Comment by pretech86** [comment]
whats up use the QR code , how can i get otp ?

**Comment by 1256-hub-png** [comment]
I can't set up this all tools please sujest me
