### ISSUE TITLE
Ngrok not working. showing wrong url.

### ISSUE THREAD

**Issue by Akshay-Arjun** [Ignitetch/AdvPhishing#147]
![image](https://user-images.githubusercontent.com/68991993/152636682-022a0925-791c-4f20-be52-a1d6ea6457e3.png)

**Comment by Erasmo254** [comment]
![Screenshot_20220213-023405_Termux](https://user-images.githubusercontent.com/65860549/153733073-7a1ab643-e955-482b-ba15-e9e583eec8c8.jpg)
Link parts missing

**Comment by Akshay-Arjun** [comment]
> ![Screenshot_20220213-023405_Termux](https://user-images.githubusercontent.com/65860549/153733073-7a1ab643-e955-482b-ba15-e9e583eec8c8.jpg) Link parts missing

Yes. @Ignitetch can you look into this?

**Comment by The-Boss-Hacker** [comment]
> ![Screenshot_20220213-023405_Termux](https://user-images.githubusercontent.com/65860549/153733073-7a1ab643-e955-482b-ba15-e9e583eec8c8.jpg) Link parts missing
**Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv

**Comment by The-Boss-Hacker** [comment]
**Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv

**Comment by The-Boss-Hacker** [comment]
**Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv

**Comment by Akshay-Arjun** [comment]
More better use this https://github.com/Akshay-Arjun/69phisher .
No need of NGROK and completely undetectable by webbrowsers like chrome .
