### ISSUE TITLE
Link not generating

### ISSUE THREAD

**Issue by Expert-Hacker** [Ignitetch/AdvPhishing#15]
Link not generating even mobile hotspot is on.. please help

**Comment by Ignitetch** [comment]
before execute of tool you need to open your mobile data and hostspot

**Comment by KaravaliStudio** [comment]
Yes,now link not showing issue has resolved but some time web page
background image not working.. showing like this below screenshot mentioned

**Comment by Ignitetch** [comment]
Ok

I will check own smartphone then I confirm you what’s the issue


Thanks

**Comment by KaravaliStudio** [comment]
Ok..try without root method

**Comment by sanelez** [comment]
HI

i get this error when i run the script ( ./facebook.sh: line 76: jq: command not found
(23) Failed writing body )

Does any one know how to solve it

**Comment by NaveenNirban** [comment]
Checkout this video.
https://youtu.be/1PRjOhLJrTA

**Comment by mohantirumalasetti** [comment]
i just solved the issue just clone it from https://github.com/mohantirumalasetti/AdvPhishing
