### ISSUE TITLE
Redirect to Localhost Port 80

### ISSUE THREAD

**Issue by adrhmnhkm** [Ignitetch/AdvPhishing#16]
I have tried your tool but i had problem . Why ngrok's link just redirect to my local port 80 ? and it opens my local web server .

**Comment by Ignitetch** [comment]
please start tool after follow the intruction

**Comment by dedshit** [comment]
> I have tried your tool but i had problem . Why ngrok's link just redirect to my local port 80 ? and it opens my local web server .


damn nigga just contact me on whatsapp i fixed that shit too
wa.me/+918428425154
