### ISSUE TITLE
AdvPhishing Not Working I am Fixed Come Here guys

### ISSUE THREAD

**Issue by thebosshacker-in** [Ignitetch/AdvPhishing#163]
Deleted

**Comment by novrizaledward** [comment]
> **Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv



> **Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv

your code not working, can you fix again ?

**Comment by The-Boss-Hacker** [comment]
> > **Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv
> 
> > **Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv
> 
> your code not working, can you fix again ?

> What Error ❓

**Comment by NeerajCodz** [comment]
Try https://github.com/Alygnt/Clifty it has more page and more features

**Comment by CEADTH** [comment]
> > > **Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv
> > 
> > > **Use The Tool** = https://github.com/The-Boss-Hacker/BossAdv
> > 
> > your code not working, can you fix again ?
> 
> > What Error ❓

Bash AdvPhishing.sh is not working
