### ISSUE TITLE
problem with Ngrok

### ISSUE THREAD

**Issue by sahilvinodMhatre** [Ignitetch/AdvPhishing#2]
come times ngrok close connection and due to it the phishing page do not loads up
this error occurs on webpage : 

Too Many Connections

Too many connections! The tunnel session '1aDW7ClAkCW1c2ut8BnN' has violated the rate-limit policy of 20 connections per minute by initiating 23 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702

**Comment by Ignitetch** [comment]
Hi
Due to ngrok plan, Must be log in ngrok.

Solve

First exeute this file
./setup.sh   —Linux
./startup.sh  —termux

When they want ngrok token then login ngrok site and copy the token and
paste it .
