### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sanderwulp** [Ignitetch/AdvPhishing#21]
G

**Comment by dedshit** [comment]
lol i fixed that thing .
If u want that contact me on whatsapp 

wa.me/+918428425154

**Comment by Ignitetch** [comment]
First give me screenshots of error then I contact you


Thanks

**Comment by dedshit** [comment]
everything is error 🤣🤣

**Comment by dedshit** [comment]
anyhow your technique is gud 👍👍👍👍

**Comment by dedshit** [comment]
> G

lol 🤣🤣

**Comment by dedshit** [comment]
> G

dumbass just learn shell script then u can do anything u want
