### ISSUE TITLE
syntax error near unexpected token

### ISSUE THREAD

**Issue by rktanwar820** [Ignitetch/AdvPhishing#31]
./An-AdvPhishing.sh: line 752: syntax error near unexpected token `;;'
![Screenshot_2020-05-22-17-05-20-14_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65767414/82664000-7145bf80-9c4e-11ea-9a84-839ab6b12a96.jpg)

**Comment by Ignitetch** [comment]
donot select the option with zero.
