### ISSUE TITLE
Link is not generating

### ISSUE THREAD

**Issue by sanderwulp** [Ignitetch/AdvPhishing#35]
[

**Comment by D3vGruU** [comment]
You can use this https://github.com/D3vGruU/TermuxNGROK.git 

And configure NGROK separately and use

**Comment by An-EnD** [comment]
i am using kali linux, same issue. No link is being generated

**Comment by D3vGruU** [comment]
Download ngrok for linux separately and use The Advphising and keep the
server as localhost at your choice of port(eg:8080) and run ngrok in
separate terminal with command ./ngrok http 8080 same choice of port you
need.
And before using that ngrok command config auth token.
