### ISSUE TITLE
Send this link to the target: // CREDENTIAL //

### ISSUE THREAD

**Issue by khandakeranikajuhi** [Ignitetch/AdvPhishing#36]
After reaching there, I can't get anything after seeing 
[ <<>> ] Send this link to the Target : 
// CREDENTIAL //

How to go to the next steps?
Please help me.

**Comment by 7492singh** [comment]
same problem with me

**Comment by HackersStation** [comment]
That is because, your ngrok server may not have started...
So try turning on your mobile data and hotspot and connectiing to any
device...

**Comment by Ignitetch** [comment]
Run the command properly and step by step and I'm pretty sure the error will go away.

**Comment by Phantandaf** [comment]
Samo samo here
