### ISSUE TITLE
Error when accesing the ngrok url

### ISSUE THREAD

**Issue by amarCosmospace** [Ignitetch/AdvPhishing#37]
hi,
i'm getting this error when i try any of the phishing tools.
"The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it."

<img width="1215" alt="Capture d’écran 2020-07-09 à 17 47 06" src="https://user-images.githubusercontent.com/22593354/87061684-57673880-c20c-11ea-969c-35984f118087.png">

Any idea ?

**Comment by fgabcy** [comment]
> hi,
> i'm getting this error when i try any of the phishing tools.
> "The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it."
> 
> <img alt="Capture d’écran 2020-07-09 à 17 47 06" width="1215" src="https://user-images.githubusercontent.com/22593354/87061684-57673880-c20c-11ea-969c-35984f118087.png">
> 
> Any idea ?

Did you set proxy IP on your browser?

**Comment by Ignitetch** [comment]
no
i don't see this kind of error

**Comment by amarCosmospace** [comment]
no, i didnt use a proxy
