### ISSUE TITLE
Send the link is not available

### ISSUE THREAD

**Issue by Yahyaotaif** [Ignitetch/AdvPhishing#42]
Send the link to the target is empty when choosing 21. I didn't try to use it with any other social network. I tried it on both android cell phone and linux but with no luck.

![Screenshot_20200730-202246_Termux](https://user-images.githubusercontent.com/12298610/88954308-dd721e80-d2a2-11ea-80b2-67ab9d1fc041.jpg)

**Comment by Ignitetch** [comment]
Hi ,

We mentioned the different commands for kali Linux and it also work fine in
termux because I personally check regularly. But you can check the tutorial
on YouTube.

Thanks

**Comment by yashwanthalwar** [comment]
Bro..Can any one know How To Hack
 Hike Top+ And Neutrino+ Crystals...
Need Help Please 🥺
