### ISSUE TITLE
Doesn't provide a link for the target.

### ISSUE THREAD

**Issue by aiivy782** [Ignitetch/AdvPhishing#47]
AdvPhishing doesn't provide a link for the target in Termux.![33199.png](https://user-images.githubusercontent.com/46345948/90624881-58cf4c00-e221-11ea-8e95-5a249e867c14.png)

**Comment by Ignitetch** [comment]
Thanks

Ask on group which given on GitHub

**Comment by josm1** [comment]
![Screenshot_2020-08-27-19-34-19-06_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/62584897/91456954-7b0c3e00-e8a1-11ea-9d13-88129b10962e.png)
Don't show link

**Comment by sd2joshi** [comment]
Providing links

**Comment by HackersStation** [comment]
Please try turning on your hotspot in order to start the ngrok server. (In
case link doesn't generate)
