### ISSUE TITLE
System not steady at haul

### ISSUE THREAD

**Issue by sekyanzi** [Ignitetch/AdvPhishing#5]
<<>> ] Enter Your Choice : 02
./An-AdvPhishing.sh: line 419: syntax error near unexpected token `;;'
./An-AdvPhishing.sh: line 419: `                ;;'Facebook-TFO but Whatsapp-TFO is clear what's wrong with some session's

**Comment by Ignitetch** [comment]
Solution : <<>> ] Enter Your Choice : 2

**Comment by sekyanzi** [comment]
[ <<>> ] Enter Your Choice : 2

[+] // STARTING PHP SERVER //




Why does not start ngrok server yet its their installed

[+] // STARTING NGROK SERVER //

[ <<>> ] Send this link to the Target :

**Comment by Ignitetch** [comment]
Turn on Hotspot and mobile data for termux

Thank

**Comment by sekyanzi** [comment]
Seems system clear am good with it but problem is to retrieve otp code on all session's but WhatsApp I need a tutorial in retrieving otp coz have tried it with my account /accounts
