### ISSUE TITLE
Link is not opening !!

### ISSUE THREAD

**Issue by Akshay-Arjun** [Ignitetch/AdvPhishing#51]
When we open the generated link it's not opening sometimes its opening but the login details we entered are not coming to us !!

**Comment by azamet90** [comment]
it is because of free version of ngrok i think im testing it now it looks cool but i was not able to test it because of the connection limits of ngrok :-/

**Comment by Ignitetch** [comment]
Bro add ngrok token

**Comment by Ignitetch** [comment]
yes

**Comment by NeerajCodz** [comment]
Try https://github.com/Alygnt/Clifty it has more page and more features
