### ISSUE TITLE
Problem with ngrok link

### ISSUE THREAD

**Issue by midusgrey** [Ignitetch/AdvPhishing#7]
![Screenshot_2020-04-16_19-01-28](https://user-images.githubusercontent.com/61030942/79484909-b275fe80-8014-11ea-93d2-eb9a492137a9.png)

**Comment by sekyanzi** [comment]
Try termux it install automatic just bare the ngro.Authe code

**Comment by m1dux** [comment]
Paytm is working fine, but why Adv doesn't?

**Comment by Ignitetch** [comment]
please enter the ngrok token

**Comment by Ignitetch** [comment]
ngrok token options is in setup or start file..

**Comment by m1dux** [comment]
I already done that..
I did it with Paytm too and it worked fine but ADv showing me this message.. it worked fine when I downloaded it but when I rebooted kali Linux the ngrok that happened when I opened the link from ngrok..

**Comment by NaveenNirban** [comment]
Check Out this video ,it might help you.
https://youtu.be/1PRjOhLJrTA

**Comment by D3vGruU** [comment]
As you said when it gets rebooted u need to configure the ngrok with same details of ip u already used to make the tunnel active again,if not just create a new tunnel with new config and in termux due to some lack of support ngrok tunneling strucks sometime.

**Comment by Ignitetch** [comment]
definatly right 🥇

**Comment by Ignitetch** [comment]
It being happen due to lack of ngrok support in termux.

**Comment by DB2121** [comment]
Issues with the generated link
It's usually like this Facebook.com@
