### ISSUE TITLE
Editing the number in Paypal

### ISSUE THREAD

**Issue by kennytriplex** [Ignitetch/AdvPhishing#76]
How to change the number in PayPal? 
![Screenshot_2020-12-30-08-35-26](https://user-images.githubusercontent.com/24676273/103336954-0aa54180-4a7a-11eb-9613-712882d8aeb5.png)

**Comment by Magic1369** [comment]
Baap sa panga nhi😂

**Comment by kennytriplex** [comment]
Solved myself
