### ISSUE TITLE
Victim password 

### ISSUE THREAD

**Issue by hariommishra** [Ignitetch/AdvPhishing#8]
victim is entering their password , keyboard is only allowing numbers , if password is alphanumeric , can't be grab ...please patch it fast . thank you !

**Comment by hariommishra** [comment]
![Screenshot_2020-04-17-19-58-10-16](https://user-images.githubusercontent.com/38611845/79584284-d0faf900-80eb-11ea-9fa5-a0b3e4bf9554.png)

**Comment by Ignitetch** [comment]
Hii

Thanks man for find this bug

Thanks

**Comment by hariommishra** [comment]
Sir my report is not patched yet
Try to patch .
Can we add custom pages here?

**Comment by Ignitetch** [comment]
Hii

Ok I will disscuss and patch it.

Thanks
