### ISSUE TITLE
/ngrok: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by teknosmanli** [Ignitetch/AdvPhishing#9]
/ngrok: cannot execute binary file: Exec format error
what is problem i am use kali 2020 last version x86

**Comment by Ignitetch** [comment]
Hii

Try this form starting

   - git clone https://github.com/Ignitetch/AdvPhishing.git
   - cd AdvPhishing/
   - chmod 777 setup.sh
   - ./setup.sh
   - ./AdvPhishing

**Comment by teknosmanli** [comment]
the error continues my brother

**Comment by Ignitetch** [comment]
Hii

I already made a tutorial please checkout on my GitHub page.

Thanks

**Comment by dedshit** [comment]
> /ngrok: cannot execute binary file: Exec format error
> what is problem i am use kali 2020 last version x86


nigga first check ur architecture and download ngrok based on that 🤣🤣

**Comment by j-dogcoder** [comment]
This is still happening for me.

**Comment by 008karan** [comment]
I just switched LinuxARM64 with Linux 32 bit and it worked!

**Comment by proevox** [comment]
estou utilizando termux no telefone de arquitetura ARM, só fiz o download do ngrok ARM e executei deu certo
